#include <gui/compositor.h>
#include <gui/framebuffer.h>
#include <gui/shell.h>
#include <gui/nova_apps.h>
#include <gui/browser.h>
#include <gui/editor.h>
#include <gui/window.h>
#include <drivers/mouse.h>
#include <drivers/keyboard.h>
#include <kernel/pit.h>
#include <kernel/scheduler.h>
#include <kernel/apic.h>
#include <kernel/nova.h>
#include <kernel/power.h>
#include <kernel/pmm.h>
#include <net/net.h>
#include <fs/fat32.h>
#include <string.h>

#define DOOM_BLIT_W 320
#define DOOM_BLIT_H 200
#define TOP_H 48
#define SIDE_W 196
#define DOCK_H 66
#define MAX_TERMINAL 8192
#define MAX_INPUT 160
#define BROWSER_URL_CAP 256

static const uint32_t BG0=0x050713, BG1=0x10152A, PANEL=0x11182B, PANEL2=0x192440;
static const uint32_t CARD=0x0C1323, BORDER=0x304266, TEXT=0xF7F9FF, MUTED=0x93A4C7;
static const uint32_t CYAN=0x55E7FF, BLUE=0x5C83FF, PURPLE=0xC05CFF, PINK=0xFF4FCB;
static const uint32_t GREEN=0x65F2B1, AMBER=0xFFD166, RED=0xFF557D;

static uint32_t fullscreen_buffer[DOOM_BLIT_W*DOOM_BLIT_H];
static int fullscreen_active, fullscreen_owner=-1;
static enum nova_app_id active_app=NOVA_APP_HOME;
static int launcher_open, control_open, notices_open, window_mode, previous_left;
static int terminal_pid=-1;
static uint32_t terminal_cwd;
static char terminal_output[MAX_TERMINAL];
static int terminal_output_len;
static char terminal_input[MAX_INPUT];
static int terminal_input_len;
static struct fat_dirent_info files[18];
static int file_count;
static struct nova_browser browser_state;
static char browser_url[BROWSER_URL_CAP];
static int browser_url_len;
static struct nova_editor editor_state;
static int terminal_window=-1, browser_window=-1, editor_window=-1;

static int inside(int px,int py,int x,int y,int w,int h){return px>=x&&py>=y&&px<x+w&&py<y+h;}
static void u32s(uint32_t v,char*out){char t[16];int n=0;if(!v){out[0]='0';out[1]=0;return;}while(v&&n<15){t[n++]=(char)('0'+v%10);v/=10;}for(int i=0;i<n;i++)out[i]=t[n-1-i];out[n]=0;}
static void append_text(const char*s){if(!s)return;int n=(int)strlen(s);if(n<=0)return;if(n>=MAX_TERMINAL){s+=n-(MAX_TERMINAL-1);n=MAX_TERMINAL-1;}if(terminal_output_len+n>=MAX_TERMINAL){int d=terminal_output_len+n-MAX_TERMINAL+1;memmove(terminal_output,terminal_output+d,terminal_output_len-d);terminal_output_len-=d;}memcpy(terminal_output+terminal_output_len,s,n);terminal_output_len+=n;terminal_output[terminal_output_len]=0;}
void terminal_route_output(int pid,const char*s){if(pid==terminal_pid)append_text(s);}
void gui_blit_fullscreen(const uint32_t*pixels,int owner_pid){if(!pixels)return;memcpy(fullscreen_buffer,pixels,sizeof(fullscreen_buffer));fullscreen_active=1;fullscreen_owner=owner_pid;}

static uint32_t accent(void){struct nova_settings s;nova_settings_get(&s);return s.accent==1?PURPLE:s.accent==2?GREEN:s.accent==3?AMBER:CYAN;}
static uint32_t sev(uint8_t s){return s==NOVA_SUCCESS?GREEN:s==NOVA_WARNING?AMBER:s==NOVA_ERROR?RED:BLUE;}
static void panel(int x,int y,int w,int h,int r,uint32_t c){fb_fill_rounded_rect(x+5,y+7,w,h,r,0x02030A);fb_fill_rounded_rect(x,y,w,h,r,c);fb_draw_rect(x,y,w,h,BORDER);}
static void glow_line(int x,int y,int w,uint32_t c){fb_fill_rect(x,y,w,1,c);fb_fill_rect(x,y+1,w,1,c);}
static void orb(int cx,int cy,int r,uint32_t c,int a){for(int y=-r;y<=r;y+=3)for(int x=-r;x<=r;x+=3){int d=x*x+y*y;if(d<=r*r)fb_blend_pixel(cx+x,cy+y,c,(uint8_t)(5+((r*r-d)*a)/(r*r)));}}

static void wallpaper(void){int w=(int)fb_width(),h=(int)fb_height();fb_fill_gradient_v(0,0,w,h,BG1,BG0);uint32_t t=pit_ticks();orb(w-130+(int)((t/8)%80),110,210,PURPLE,80);orb(w/2,h-90,250,BLUE,65);orb(80,180,170,PINK,55);for(int y=0;y<h;y+=28)fb_draw_line(0,y,w,y,0x0B1120);for(int x=0;x<w;x+=28)fb_draw_line(x,0,x,h,0x09101C);for(int i=0;i<24;i++){int x=(i*97+(int)t/3)%w;int y=(i*53+(int)t/5)%h;fb_fill_rect(x,y,2,2,i%3?CYAN:PINK);}}

static void topbar(void){int w=(int)fb_width();fb_fill_rect(0,0,w,TOP_H,PANEL);glow_line(0,TOP_H-2,w,accent());fb_fill_rounded_rect(12,8,32,32,10,accent());fb_draw_string(22,19,"Z",BG0,2);fb_draw_string(54,12,"ZAPOS NOVA",TEXT,2);fb_draw_string(54,32,"MAXIMAL SYSTEM EDITION",MUTED,1);const struct nova_app_descriptor*a=nova_app_get(active_app);fb_fill_rounded_rect(260,10,210,28,14,PANEL2);fb_fill_rounded_rect(272,18,10,10,5,a->accent);fb_draw_string(292,19,a->name,TEXT,1);char up[16];u32s(pit_ticks()/100,up);fb_draw_string(w-390,13,"UPTIME",MUTED,1);fb_draw_string(w-390,29,up,TEXT,1);fb_draw_string(w-305,13,"TASKS",MUTED,1);char tc[8];u32s((uint32_t)scheduler_task_count(),tc);fb_draw_string(w-305,29,tc,GREEN,1);fb_fill_rounded_rect(w-210,9,42,30,12,window_mode?PANEL2:CARD);fb_draw_string(w-199,19,"WIN",CYAN,1);fb_fill_rounded_rect(w-160,9,38,30,12,notices_open?PANEL2:CARD);fb_draw_string(w-146,19,"!",AMBER,1);fb_fill_rounded_rect(w-114,9,38,30,12,control_open?PANEL2:CARD);fb_draw_string(w-100,19,"#",CYAN,1);fb_fill_rounded_rect(w-68,9,52,30,12,RED);fb_draw_string(w-57,19,"OFF",TEXT,1);}

static void sidebar(void){int h=(int)fb_height();fb_fill_rect(0,TOP_H,SIDE_W,h-TOP_H,0x09101D);fb_fill_rect(SIDE_W-1,TOP_H,1,h-TOP_H,BORDER);fb_draw_string(16,TOP_H+18,"COMMAND MATRIX",MUTED,1);for(int i=0;i<nova_app_count();i++){const struct nova_app_descriptor*a=nova_app_at(i);int y=TOP_H+40+i*36;if(a->id==active_app){fb_fill_rounded_rect(10,y,SIDE_W-20,30,9,PANEL2);fb_fill_rect(10,y+6,4,18,a->accent);}fb_fill_rounded_rect(24,y+5,20,20,6,a->accent);fb_draw_string(30,y+11,a->glyph,BG0,1);fb_draw_string(56,y+10,a->name,a->id==active_app?TEXT:MUTED,1);}panel(10,h-126,SIDE_W-20,104,14,CARD);fb_draw_string(24,h-110,"LIVE CORE GRID",TEXT,1);for(int i=0;i<16;i++){int bh=8+((i*17+(int)(pit_ticks()/2))%44);uint32_t c=i%4==0?CYAN:i%4==1?PURPLE:i%4==2?PINK:GREEN;fb_fill_rounded_rect(24+i*9,h-42-bh,5,bh,3,c);}fb_draw_string(24,h-34,apic_ap_started_count()?"SMP ONLINE":"BSP ONLY",apic_ap_started_count()?GREEN:AMBER,1);}

static void heading(int x,int y,const char*t,const char*s){fb_draw_string(x,y,t,TEXT,2);fb_draw_string(x,y+28,s,MUTED,1);}
static void stat(int x,int y,int w,const char*l,const char*v,uint32_t c){panel(x,y,w,88,15,CARD);fb_fill_rounded_rect(x+14,y+14,30,30,10,c);fb_draw_string(x+25,y+25,"+",BG0,1);fb_draw_string(x+56,y+16,l,MUTED,1);fb_draw_string(x+56,y+42,v,TEXT,2);fb_fill_rounded_rect(x+14,y+70,w-28,4,2,PANEL2);fb_fill_rounded_rect(x+14,y+70,(w-28)*3/4,4,2,c);}

static void home(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"NOVA COMMAND CITADEL","Dense live telemetry, native applications and kernel services in one surface.");char tasks[8],events[8],frames[16],cores[4];u32s((uint32_t)scheduler_task_count(),tasks);u32s((uint32_t)nova_event_count(),events);u32s(pmm_free_frame_count(),frames);cores[0]=apic_ap_started_count()?'2':'1';cores[1]=0;int cw=(w-30)/4;stat(x,y+58,cw,"TASKS",tasks,CYAN);stat(x+cw+10,y+58,cw,"EVENTS",events,PURPLE);stat(x+(cw+10)*2,y+58,cw,"FREE FRAMES",frames,GREEN);stat(x+(cw+10)*3,y+58,cw,"CPUS",cores,AMBER);int py=y+162,left=w*2/3;panel(x,py,left,286,18,CARD);fb_draw_string(x+18,py+18,"SYSTEM TOPOLOGY",MUTED,1);for(int i=0;i<8;i++){int nx=x+24+(i%4)*132,ny=py+48+(i/4)*96;uint32_t c=i%4==0?CYAN:i%4==1?PURPLE:i%4==2?PINK:GREEN;fb_fill_rounded_rect(nx,ny,112,72,14,PANEL2);fb_fill_rounded_rect(nx+12,ny+12,28,28,10,c);fb_draw_string(nx+22,ny+22,"*",BG0,1);const char*names[]={"KERNEL","SCHED","MEMORY","FILES","NETWORK","RUNTIME","NOVA","DISPLAY"};fb_draw_string(nx+12,ny+49,names[i],TEXT,1);}fb_draw_string(x+20,py+252,"Press 1-9 for apps | WIN opens movable windows | ` toggles mode",MUTED,1);int rx=x+left+12,rw=w-left-12;panel(rx,py,rw,286,18,CARD);fb_draw_string(rx+16,py+18,"ACTIVITY STREAM",TEXT,1);for(int i=0;i<7;i++){struct nova_event e;if(!nova_event_read(i,&e))break;int ry=py+52+i*30;fb_fill_rounded_rect(rx+16,ry,9,9,5,sev(e.severity));fb_draw_string(rx+34,ry,e.source,sev(e.severity),1);fb_draw_string(rx+112,ry,e.text,TEXT,1);}}

static void draw_terminal_text(int x,int y,int w,int h){int cols=w/8,rows=h/14,total=1;for(int i=0;i<terminal_output_len;i++)if(terminal_output[i]=='\n')total++;int skip=total>rows?total-rows:0,line=0,row=0,col=0,bl=0;char b[128];for(int i=0;i<=terminal_output_len;i++){char c=i==terminal_output_len?'\n':terminal_output[i];if(c=='\n'||col>=cols||bl>=126){if(line>=skip&&row<rows){b[bl]=0;fb_draw_string(x,y+row*14,b,TEXT,1);row++;}line++;col=0;bl=0;if(c=='\n')continue;}if(c>=32&&c<127){b[bl++]=c;col++;}}}
static void terminal(void){int x=SIDE_W+22,y=TOP_H+18,w=(int)fb_width()-x-18,h=(int)fb_height()-y-DOCK_H-16;panel(x,y,w,h,18,0x050910);fb_fill_rounded_rect(x+16,y+14,12,12,6,RED);fb_fill_rounded_rect(x+34,y+14,12,12,6,AMBER);fb_fill_rounded_rect(x+52,y+14,12,12,6,GREEN);fb_draw_string(x+82,y+17,"ROOT CONSOLE // NATIVE EXECUTION FABRIC",MUTED,1);glow_line(x+16,y+40,w-32,PURPLE);draw_terminal_text(x+18,y+54,w-36,h-108);fb_fill_rounded_rect(x+16,y+h-42,w-32,28,9,PANEL);fb_draw_string(x+26,y+h-32,">",CYAN,1);fb_draw_string(x+44,y+h-32,terminal_input,TEXT,1);if((pit_ticks()/35)%2==0)fb_fill_rect(x+44+fb_text_width(terminal_input,1),y+h-33,7,10,CYAN);}

static void files_view(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"FILES // STORAGE MATRIX","Direct FAT32 workspace access with live metadata.");panel(x,y+58,w,(int)fb_height()-y-DOCK_H-78,18,CARD);for(int i=0;i<file_count;i++){int col=i%3,row=i/3;int fx=x+18+col*((w-48)/3),fy=y+82+row*62;fb_fill_rounded_rect(fx,fy,(w-60)/3,50,12,PANEL2);fb_fill_rounded_rect(fx+10,fy+10,28,28,9,files[i].is_dir?AMBER:BLUE);fb_draw_string(fx+18,fy+20,files[i].is_dir?"D":"F",BG0,1);fb_draw_string(fx+50,fy+12,files[i].name,TEXT,1);char sz[12];u32s(files[i].size,sz);fb_draw_string(fx+50,fy+30,files[i].is_dir?"DIRECTORY":sz,MUTED,1);}}

static void tasks_view(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"TASK ORCHESTRATOR","Live scheduler state across kernel and user processes.");panel(x,y+58,w,(int)fb_height()-y-DOCK_H-78,18,CARD);fb_draw_string(x+18,y+78,"PID",MUTED,1);fb_draw_string(x+92,y+78,"STATE",MUTED,1);fb_draw_string(x+220,y+78,"CLASS",MUTED,1);fb_draw_string(x+370,y+78,"ACTIVITY",MUTED,1);int count=scheduler_task_count();for(int i=0;i<count&&i<16;i++){int ry=y+104+i*28;if(i%2==0)fb_fill_rounded_rect(x+14,ry-5,w-28,24,7,0x121B2E);char p[8];u32s((uint32_t)i,p);enum task_state s=scheduler_task_state(i);fb_draw_string(x+20,ry,p,TEXT,1);fb_fill_rounded_rect(x+92,ry,8,8,4,s==TASK_RUNNING?GREEN:s==TASK_READY?BLUE:RED);fb_draw_string(x+110,ry,s==TASK_RUNNING?"RUNNING":s==TASK_READY?"READY":"ENDED",TEXT,1);fb_draw_string(x+220,ry,i==0?"BOOT CORE":"SCHEDULED",MUTED,1);for(int b=0;b<16;b++)fb_fill_rounded_rect(x+370+b*11,ry,7,8,3,(b<(i*7+(int)(pit_ticks()/4))%16)?(i%2?PURPLE:CYAN):PANEL2);}}

static void browser_view(void){int x=SIDE_W+22,y=TOP_H+18,w=(int)fb_width()-x-18,h=(int)fb_height()-y-DOCK_H-16;panel(x,y,w,h,18,CARD);fb_draw_string(x+18,y+17,"NOVA BROWSER",TEXT,1);fb_fill_rounded_rect(x+132,y+10,w-230,30,11,PANEL2);fb_draw_string(x+146,y+20,browser_url_len?browser_url:"http://example.com",browser_url_len?TEXT:MUTED,1);fb_fill_rounded_rect(x+w-86,y+10,66,30,11,CYAN);fb_draw_string(x+w-68,y+20,"GO",BG0,1);glow_line(x+16,y+48,w-32,CYAN);if(browser_state.loading)fb_draw_string(x+20,y+70,"Loading document...",AMBER,1);else if(browser_state.error)fb_draw_string(x+20,y+70,browser_state.title,RED,1);else if(!browser_state.dom){fb_draw_string(x+20,y+70,"Enter a URL and press Enter. HTTP, TLS, DOM, CSS and layout are native.",MUTED,1);}else{fb_draw_string(x+20,y+64,browser_state.title,TEXT,1);char status[12];u32s((uint32_t)browser_state.status,status);fb_draw_string(x+w-80,y+64,status,GREEN,1);int ox=x+20,oy=y+88-browser_state.scroll_y;for(int i=0;i<browser_state.layout.item_count;i++){struct layout_item*it=&browser_state.layout.items[i];int iy=oy+it->y;if(iy<y+82||iy>y+h-18)continue;if(it->type==LAYOUT_ITEM_RECT){if(it->has_gradient){if(it->gradient_horizontal)fb_fill_gradient_h(ox+it->x,iy,it->w,it->h,it->color,it->color2);else fb_fill_gradient_v(ox+it->x,iy,it->w,it->h,it->color,it->color2);}else fb_fill_rounded_rect(ox+it->x,iy,it->w,it->h,it->radius,it->color);}else if(it->type==LAYOUT_ITEM_TEXT)fb_draw_string(ox+it->x,iy,it->text,it->color,1);else if(it->type==LAYOUT_ITEM_HR)fb_fill_rect(ox+it->x,iy,it->w,it->h,it->color);else if(it->type==LAYOUT_ITEM_IMAGE&&it->pixels)fb_blit_rgb(ox+it->x,iy,it->w,it->h,it->pixels,it->w,it->h);}}}

static void editor_view(void){int x=SIDE_W+22,y=TOP_H+18,w=(int)fb_width()-x-18,h=(int)fb_height()-y-DOCK_H-16;panel(x,y,w,h,18,0x080B14);fb_draw_string(x+18,y+17,"NOVA EDITOR",TEXT,1);fb_draw_string(x+132,y+17,editor_state.filename,editor_state.dirty?AMBER:GREEN,1);fb_fill_rounded_rect(x+w-176,y+10,70,30,10,PANEL2);fb_draw_string(x+w-157,y+20,"NEW",TEXT,1);fb_fill_rounded_rect(x+w-96,y+10,76,30,10,PINK);fb_draw_string(x+w-76,y+20,"SAVE",BG0,1);glow_line(x+16,y+48,w-32,PINK);fb_fill_rect(x+16,y+58,46,h-76,0x0E1627);uint32_t line=1;char ln[12];u32s(line,ln);fb_draw_string(x+24,y+66,ln,MUTED,1);int px=x+72,py=y+66;for(uint32_t i=0;i<editor_state.len;i++){char c=editor_state.text[i];if(c=='\n'){line++;u32s(line,ln);py+=14;px=x+72;fb_draw_string(x+24,py,ln,MUTED,1);continue;}char one[2]={c,0};fb_draw_string(px,py,one,(c>='0'&&c<='9')?AMBER:(c=='"'||c=='\'')?GREEN:TEXT,1);px+=8;if(px>x+w-24){py+=14;px=x+72;}if(py>y+h-22)break;}if((pit_ticks()/35)%2==0&&editor_state.cursor==editor_state.len)fb_fill_rect(px,py,7,11,PINK);}

static void activity_view(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"KERNEL EVENT CASCADE","Every service transition, subsystem decision and notification.");panel(x,y+58,w,(int)fb_height()-y-DOCK_H-78,18,CARD);for(int i=0;i<nova_event_count()&&i<18;i++){struct nova_event e;if(!nova_event_read(i,&e))continue;int ry=y+80+i*26;fb_fill_rounded_rect(x+18,ry,10,10,5,sev(e.severity));fb_draw_string(x+42,ry,e.source,sev(e.severity),1);fb_draw_string(x+166,ry,e.text,TEXT,1);char t[12];u32s(e.tick,t);fb_draw_string(x+w-96,ry,t,MUTED,1);}}

static void settings_view(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"NOVA VISUAL REACTOR","Tune color, density, motion and performance behavior.");struct nova_settings s;nova_settings_get(&s);const char*names[]={"ACCENT CYCLE","REDUCED MOTION","COMPACT MODE","PERFORMANCE MODE","CLOCK SECONDS","SAVE NOVA.CFG"};int vals[]={1,s.reduced_motion,s.compact_mode,s.performance_mode,s.show_seconds,1};for(int i=0;i<6;i++){int col=i%2,row=i/2;int bx=x+col*((w-12)/2+12),by=y+66+row*92,bw=(w-12)/2;panel(bx,by,bw,78,14,CARD);fb_draw_string(bx+18,by+18,names[i],TEXT,1);fb_draw_string(bx+18,by+42,i==5?"Persist current desktop state":"Click to toggle or cycle",MUTED,1);fb_fill_rounded_rect(bx+bw-68,by+22,48,28,14,vals[i]?accent():PANEL2);fb_fill_rounded_rect(bx+bw-(vals[i]?43:63),by+28,16,16,8,TEXT);}}

static void system_view(void){int x=SIDE_W+24,y=TOP_H+20,w=(int)fb_width()-x-20;heading(x,y,"SYSTEM ARCHITECTURE","A from-scratch x86 operating system with a maximalist service shell.");const char*names[]={"MULTIBOOT","PAGING","PMM + HEAP","SMP SCHEDULER","RING 3","ELF LOADER","TCP/IP + TLS","FAT32","JS ENGINE","PY RUNTIME","C COMPILER","NOVA SERVICES"};for(int i=0;i<12;i++){int col=i%3,row=i/3;int bx=x+col*((w-24)/3+12),by=y+64+row*78,bw=(w-24)/3;panel(bx,by,bw,64,13,CARD);uint32_t c=i%4==0?CYAN:i%4==1?PURPLE:i%4==2?PINK:GREEN;fb_fill_rounded_rect(bx+14,by+14,10,36,5,c);fb_draw_string(bx+38,by+18,names[i],TEXT,1);fb_draw_string(bx+38,by+40,"ONLINE",c,1);}}

static void dock(void){int w=(int)fb_width(),h=(int)fb_height();int dw=704,x=(w-dw)/2,y=h-DOCK_H+8;panel(x,y,dw,50,16,0x121A2D);for(int i=0;i<nova_app_count();i++){const struct nova_app_descriptor*a=nova_app_at(i);int bx=x+12+i*74;fb_fill_rounded_rect(bx,y+8,56,34,11,a->id==active_app?PANEL2:CARD);fb_fill_rounded_rect(bx+9,y+11,28,28,9,a->accent);fb_draw_string(bx+17,y+21,a->glyph,BG0,1);if(a->id==active_app)fb_fill_rounded_rect(bx+20,y+44,16,3,2,a->accent);}fb_fill_rounded_rect(x+dw-44,y+8,32,34,11,window_mode?GREEN:PINK);fb_draw_string(x+dw-35,y+20,window_mode?"W":"+",BG0,1);}

static void draw_window_frame(struct nova_window*w){if(!w||!(w->flags&NOVA_WINDOW_VISIBLE)||(w->flags&NOVA_WINDOW_MINIMIZED))return;panel(w->x,w->y,w->w,w->h,14,CARD);fb_fill_rounded_rect(w->x,w->y,w->w,32,14,PANEL2);fb_fill_rect(w->x,w->y+28,w->w,4,PANEL2);fb_fill_rounded_rect(w->x+10,w->y+10,10,10,5,w->accent);fb_draw_string(w->x+30,w->y+10,w->title,TEXT,1);fb_fill_rounded_rect(w->x+w->w-54,w->y+8,14,14,5,AMBER);fb_fill_rounded_rect(w->x+w->w-32,w->y+8,14,14,5,RED);fb_fill_rounded_rect(w->x+w->w-14,w->y+w->h-14,10,10,3,w->accent);if(w->app_id==NOVA_APP_TERMINAL)draw_terminal_text(w->x+12,w->y+42,w->w-24,w->h-54);else if(w->app_id==NOVA_APP_BROWSER){fb_draw_string(w->x+12,w->y+44,browser_state.title[0]?browser_state.title:"Browser ready",TEXT,1);fb_draw_string(w->x+12,w->y+64,browser_state.url[0]?browser_state.url:"Enter URL in full browser workspace",MUTED,1);}else if(w->app_id==NOVA_APP_EDITOR){fb_draw_string(w->x+12,w->y+44,editor_state.filename,TEXT,1);fb_draw_string(w->x+12,w->y+64,editor_state.dirty?"Unsaved changes":"Saved",editor_state.dirty?AMBER:GREEN,1);}}
static void windows_overlay(void){if(!window_mode)return;for(int i=0;i<nova_wm_count();i++)draw_window_frame(nova_wm_at_z(i));}

static void overlay_panels(void){int w=(int)fb_width();if(notices_open){int x=w-382,y=TOP_H+10;panel(x,y,364,388,18,PANEL);fb_draw_string(x+18,y+18,"NOTIFICATION STACK",TEXT,1);for(int i=0;i<nova_notice_count()&&i<6;i++){struct nova_notice n;if(!nova_notice_read(i,&n))continue;int ny=y+50+i*52;fb_fill_rounded_rect(x+14,ny,336,42,11,CARD);fb_fill_rounded_rect(x+26,ny+15,10,10,5,sev(n.severity));fb_draw_string(x+48,ny+9,n.title,TEXT,1);fb_draw_string(x+48,ny+25,n.text,MUTED,1);}}if(control_open){int x=w-344,y=TOP_H+10;panel(x,y,326,286,18,PANEL);fb_draw_string(x+18,y+18,"CONTROL CENTER",TEXT,1);const char*l[]={"ACCENT","MOTION","COMPACT","PERFORMANCE","SAVE","SHUTDOWN"};for(int i=0;i<6;i++){int bx=x+16+(i%2)*148,by=y+50+(i/2)*64;fb_fill_rounded_rect(bx,by,138,52,12,i==5?0x4A1730:CARD);fb_fill_rounded_rect(bx+12,by+14,18,18,7,i==5?RED:accent());fb_draw_string(bx+40,by+19,l[i],TEXT,1);}}}

static void cursor(int x,int y){fb_fill_triangle(x,y,x,y+22,x+15,y+15,TEXT);fb_draw_line(x,y,x,y+22,BG0);fb_draw_line(x,y,x+15,y+15,BG0);}
static void ensure_window(enum nova_app_id id){if(id==NOVA_APP_TERMINAL&&terminal_window<0)terminal_window=nova_wm_open(id,"Nova Terminal",240,100,620,360,PURPLE,NOVA_WINDOW_RESIZABLE|NOVA_WINDOW_CLOSABLE);else if(id==NOVA_APP_BROWSER&&browser_window<0)browser_window=nova_wm_open(id,"Nova Browser",310,130,650,390,CYAN,NOVA_WINDOW_RESIZABLE|NOVA_WINDOW_CLOSABLE);else if(id==NOVA_APP_EDITOR&&editor_window<0)editor_window=nova_wm_open(id,"Nova Editor",360,160,610,380,PINK,NOVA_WINDOW_RESIZABLE|NOVA_WINDOW_CLOSABLE);}
static void select_app(enum nova_app_id id){active_app=id;launcher_open=control_open=notices_open=0;nova_event_emit(NOVA_INFO,"desktop",nova_app_get(id)->name);if(id==NOVA_APP_FILES&&fat32_is_mounted())file_count=fat32_list_dir(fat32_root_cluster(),files,18);if(window_mode)ensure_window(id);}
static void toggle_setting(int i){struct nova_settings s;nova_settings_get(&s);if(i==0)s.accent=(s.accent+1)%4;else if(i==1)s.reduced_motion=!s.reduced_motion;else if(i==2)s.compact_mode=!s.compact_mode;else if(i==3)s.performance_mode=!s.performance_mode;else if(i==4)s.show_seconds=!s.show_seconds;nova_settings_set(&s);}
static void execute_terminal(void){append_text("\n> ");append_text(terminal_input);append_text("\n");terminal_pid=shell_execute(terminal_input,&terminal_cwd,append_text);terminal_input_len=0;terminal_input[0]=0;}
static void browser_go(void){if(!browser_url_len){strcpy(browser_url,"http://example.com");browser_url_len=(int)strlen(browser_url);}nova_event_emit(NOVA_INFO,"browser","Navigation started");if(nova_browser_navigate(&browser_state,browser_url,(int)fb_width()-SIDE_W-90))nova_notice_post(NOVA_SUCCESS,"Page loaded",browser_state.title);else nova_notice_post(NOVA_ERROR,"Navigation failed",browser_state.title);}
static void key(char c){if(c=='`'){window_mode=!window_mode;if(window_mode){ensure_window(NOVA_APP_TERMINAL);ensure_window(NOVA_APP_BROWSER);ensure_window(NOVA_APP_EDITOR);}return;}if(!window_mode&&active_app!=NOVA_APP_TERMINAL&&active_app!=NOVA_APP_BROWSER&&active_app!=NOVA_APP_EDITOR&&c>='1'&&c<='9'){select_app((enum nova_app_id)(c-'1'));return;}if(active_app==NOVA_APP_TERMINAL){if(c=='\n'||c=='\r')execute_terminal();else if(c=='\b'){if(terminal_input_len>0)terminal_input[--terminal_input_len]=0;}else if(c>=32&&c<127&&terminal_input_len<MAX_INPUT-1){terminal_input[terminal_input_len++]=c;terminal_input[terminal_input_len]=0;}}else if(active_app==NOVA_APP_BROWSER){if(c=='\n'||c=='\r')browser_go();else if(c=='\b'){if(browser_url_len>0)browser_url[--browser_url_len]=0;}else if(c>=32&&c<127&&browser_url_len<BROWSER_URL_CAP-1){browser_url[browser_url_len++]=c;browser_url[browser_url_len]=0;}}else if(active_app==NOVA_APP_EDITOR){if(c=='\b')nova_editor_backspace(&editor_state);else if(c=='\n'||c=='\r')nova_editor_insert(&editor_state,'\n');else if(c>=32&&c<127)nova_editor_insert(&editor_state,c);}}

static void click(int mx,int my){int w=(int)fb_width(),h=(int)fb_height();if(inside(mx,my,w-210,9,42,30)){window_mode=!window_mode;if(window_mode){ensure_window(NOVA_APP_TERMINAL);ensure_window(NOVA_APP_BROWSER);ensure_window(NOVA_APP_EDITOR);}return;}if(inside(mx,my,w-160,9,38,30)){notices_open=!notices_open;control_open=0;return;}if(inside(mx,my,w-114,9,38,30)){control_open=!control_open;notices_open=0;return;}if(inside(mx,my,w-68,9,52,30)){power_shutdown();return;}if(window_mode){int id=nova_wm_hit_test(mx,my);if(id>=0){struct nova_window*win=nova_wm_get(id);if(inside(mx,my,win->x+win->w-36,win->y+4,22,24)){nova_wm_close(id);if(id==terminal_window)terminal_window=-1;if(id==browser_window)browser_window=-1;if(id==editor_window)editor_window=-1;return;}if(inside(mx,my,win->x+win->w-58,win->y+4,22,24)){nova_wm_toggle_maximize(id);return;}active_app=(enum nova_app_id)win->app_id;nova_wm_begin_pointer(mx,my);return;}}if(control_open){int x=w-344,y=TOP_H+10;for(int i=0;i<6;i++){int bx=x+16+(i%2)*148,by=y+50+(i/2)*64;if(inside(mx,my,bx,by,138,52)){if(i<4)toggle_setting(i);else if(i==4)nova_settings_save();else power_shutdown();return;}}return;}for(int i=0;i<nova_app_count();i++){int sy=TOP_H+40+i*36;if(inside(mx,my,10,sy,SIDE_W-20,30)){select_app((enum nova_app_id)i);return;}}int dw=704,dx=(w-dw)/2,dy=h-DOCK_H+8;for(int i=0;i<nova_app_count();i++)if(inside(mx,my,dx+12+i*74,dy+8,56,34)){select_app((enum nova_app_id)i);return;}if(active_app==NOVA_APP_BROWSER){int x=SIDE_W+22,y=TOP_H+18,bw=(int)fb_width()-x-18;if(inside(mx,my,x+bw-86,y+10,66,30)){browser_go();return;}}if(active_app==NOVA_APP_EDITOR){int x=SIDE_W+22,y=TOP_H+18,ew=(int)fb_width()-x-18;if(inside(mx,my,x+ew-176,y+10,70,30)){nova_editor_new(&editor_state,"UNTITLED.TXT");return;}if(inside(mx,my,x+ew-96,y+10,76,30)){int ok=nova_editor_save(&editor_state);nova_notice_post(ok?NOVA_SUCCESS:NOVA_ERROR,ok?"File saved":"Save failed",editor_state.filename);return;}}if(active_app==NOVA_APP_SETTINGS){int x=SIDE_W+24,y=TOP_H+20,cw=((int)fb_width()-x-32)/2;for(int i=0;i<6;i++){int bx=x+(i%2)*(cw+12),by=y+66+(i/2)*92;if(inside(mx,my,bx,by,cw,78)){if(i<5)toggle_setting(i);else nova_settings_save();return;}}}}

void gui_init(void){mouse_set_bounds((int)fb_width(),(int)fb_height());terminal_cwd=fat32_is_mounted()?fat32_root_cluster():0;strcpy(terminal_output,"ZapOS Nova Maximal Edition\nKernel services online. Type help for commands.\n");terminal_output_len=(int)strlen(terminal_output);if(fat32_is_mounted())file_count=fat32_list_dir(fat32_root_cluster(),files,18);nova_browser_init(&browser_state);nova_editor_init(&editor_state,terminal_cwd);nova_editor_new(&editor_state,"UNTITLED.TXT");nova_wm_init((int)fb_width(),(int)fb_height(),TOP_H,DOCK_H);nova_notice_post(NOVA_SUCCESS,"Nova Maximal online","Browser, editor and window manager are ready.");}
void gui_run(void){uint32_t pulse=0;for(;;){if(fullscreen_active){if(scheduler_task_state(fullscreen_owner)==TASK_TERMINATED){fullscreen_active=0;fullscreen_owner=-1;}else{fb_fill_rect(0,0,(int)fb_width(),(int)fb_height(),0);fb_blit_rgb(0,0,(int)fb_width(),(int)fb_height(),fullscreen_buffer,DOOM_BLIT_W,DOOM_BLIT_H);fb_swap_buffers();pit_sleep(10);continue;}}if(pit_ticks()-pulse>=25){nova_pulse();pulse=pit_ticks();}int mx,my;uint8_t b;mouse_get_state(&mx,&my,&b);int left=(b&MOUSE_LEFT_BUTTON)!=0;if(left&&!previous_left)click(mx,my);else if(left&&previous_left&&window_mode)nova_wm_move_pointer(mx,my);else if(!left&&previous_left&&window_mode)nova_wm_end_pointer();previous_left=left;char c;while((c=keyboard_getchar())!=0)key(c);wallpaper();topbar();sidebar();if(active_app==NOVA_APP_HOME)home();else if(active_app==NOVA_APP_TERMINAL)terminal();else if(active_app==NOVA_APP_FILES)files_view();else if(active_app==NOVA_APP_TASKS)tasks_view();else if(active_app==NOVA_APP_BROWSER)browser_view();else if(active_app==NOVA_APP_EDITOR)editor_view();else if(active_app==NOVA_APP_ACTIVITY)activity_view();else if(active_app==NOVA_APP_SETTINGS)settings_view();else system_view();dock();windows_overlay();overlay_panels();cursor(mx,my);fb_swap_buffers();struct nova_settings s;nova_settings_get(&s);pit_sleep(s.performance_mode?22:10);}}
